feat: PING-3018 create verification page
BetterSocial/better-webapp-nextjs pull request #17
Opened 2023-10-31 14:20 UTC by yusufputra

create verification page for human id
<img width="355" alt="image" src="https://github.com/BetterSocial/better-webapp-nextjs/assets/13555051/fe0a2073-81a6-4d7c-babc-eb770bd7e9fb">
<img width="375" alt="image" src="https://github.com/BetterSocial/better-webapp-nextjs/assets/13555051/05ff7f46-8081-46f6-9cc3-136502b6c855">
<img width="1552" alt="image" src="https://github.com/BetterSocial/better-webapp-nextjs/assets/13555051/42de9a78-64fa-448a-a8a3-33301191a176">

2023-11-01 15:14 UTC, fajarism commented
I think the screenshot is not the same as the design Mas.
1. The design should cut the line in "...please" and start new line with "verify...". 
Meanwhile the screenshot is not.
2. The sampe applies to What is humanID description
3. There should be blue link text in "Foundation for a Human Internet"

2023-11-01 15:15 UTC, fajarism requested changes
On previous comment

2023-11-07 14:07 UTC, yusufputra commented
updated mas @fajarism

2023-11-08 03:21 UTC, fajarism approved these changes

2023-11-08 03:25 UTC, merged